title: Devin James Calligy
logo: /assets/img/Napoleon-768x506.jpg
description: I put this together because I couldn't dunk a basketball.
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
